packages:
  - apis/*
  - apps/*
  - packages/*

nodeLinker: hoisted
ignoreScripts: true
autoInstallPeers: true
strictPeerDependencies: false

allowBuilds:
  '@tailwindcss/oxide': false
  esbuild: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - sharp

overrides:
  '@types/node': 24.1.0
  '@types/react': 19.2.6
  '@types/react-dom': 19.2.3
  react: 19.2.6
  react-dom: 19.2.6
  react-icons: 5.4.0
