import { SmartTable } from 'polpo/components';
import { FaCamera, FaUser } from 'react-icons/fa';

import type { Meta, StoryObj } from '@storybook/react-vite';

const users = [
  {
    age: '25',
    gender: 'male',
    occupation: 'Software engineer',
    hobbies: ['Reading', 'Hiking'],
    email: 'john@example.com',
    phone: '123-456-7890',
    username: 'johnny25',
    name: 'John Doe',
    country: 'USA',
    id: '1',
  },
  {
    age: '30',
    gender: 'female',
    occupation: 'Graphic designer',
    hobbies: ['Painting', 'Yoga'],
    email: 'jane@example.com',
    phone: '987-654-3210',
    username: 'janeD30',
    name: 'Jane Smith',
    country: 'Canada',
    id: '2',
  },
  {
    age: '28',
    gender: 'male',
    occupation: 'Data analyst',
    hobbies: ['Gaming', 'Cycling'],
    email: 'mike@example.com',
    phone: '555-123-4567',
    username: 'mikeA28',
    name: 'Mike Johnson',
    country: 'UK',
    id: '3',
  },
  {
    age: '35',
    gender: 'female',
    occupation: 'Marketing manager',
    hobbies: ['Traveling', 'Cooking'],
    email: 'sara@example.com',
    phone: '444-987-6543',
    username: 'saraM35',
    name: 'Sara Wilson',
    country: 'Australia',
    id: '4',
  },
  {
    age: '22',
    gender: 'male',
    occupation: 'Web developer',
    hobbies: ['Programming', 'Photography'],
    email: 'alex@example.com',
    phone: '333-555-1234',
    username: 'alexD22',
    name: 'Alex Brown',
    country: 'Germany',
    id: '5',
  },
  {
    age: '27',
    gender: 'female',
    occupation: 'HR specialist',
    hobbies: ['Dancing', 'Reading'],
    email: 'lisa@example.com',
    phone: '222-444-9876',
    username: 'lisaS27',
    name: 'Lisa Davis',
    country: 'France',
    id: '6',
  },
  {
    age: '31',
    gender: 'male',
    occupation: 'Financial analyst',
    hobbies: ['Investing', 'Golfing'],
    email: 'tom@example.com',
    phone: '111-333-5555',
    username: 'tomA31',
    name: 'Tom Miller',
    country: 'Japan',
    id: '7',
  },
  {
    age: '29',
    gender: 'female',
    occupation: 'Sales executive',
    hobbies: ['Shopping', 'Running'],
    email: 'anna@example.com',
    phone: '666-222-4444',
    username: 'annaE29',
    name: 'Anna Taylor',
    country: 'Brazil',
    id: '8',
  },
  {
    age: '26',
    gender: 'male',
    occupation: 'IT support',
    hobbies: ['Gaming', 'Watching movies'],
    email: 'jake@example.com',
    phone: '777-111-3333',
    username: 'jakeS26',
    name: 'Jake Anderson',
    country: 'India',
    id: '9',
  },
  {
    age: '33',
    gender: 'female',
    occupation: 'Nurse',
    hobbies: ['Cooking', 'Painting'],
    email: 'kate@example.com',
    phone: '888-666-2222',
    username: 'kateN33',
    name: 'Kate Thomas',
    country: 'Italy',
    id: '10',
  },
  {
    age: '24',
    gender: 'male',
    occupation: 'Teacher',
    hobbies: ['Reading', 'Traveling'],
    email: 'ryan@example.com',
    phone: '999-777-1111',
    username: 'ryanT24',
    name: 'Ryan Jackson',
    country: 'Mexico',
    id: '11',
  },
  {
    age: '32',
    gender: 'female',
    occupation: 'Lawyer',
    hobbies: ['Running', 'Yoga'],
    email: 'lily@example.com',
    phone: '000-888-6666',
    username: 'lilyL32',
    name: 'Lily White',
    country: 'South Africa',
    id: '12',
  },
  {
    age: '23',
    gender: 'male',
    occupation: 'Mechanic',
    hobbies: ['Fixing cars', 'Fishing'],
    email: 'matt@example.com',
    phone: '111-999-7777',
    username: 'mattM23',
    name: 'Matt Harris',
    country: 'Russia',
    id: '13',
  },
  {
    age: '34',
    gender: 'female',
    occupation: 'Architect',
    hobbies: ['Designing', 'Hiking'],
    email: 'sophia@example.com',
    phone: '222-000-8888',
    username: 'sophiaA34',
    name: 'Sophia Clark',
    country: 'Spain',
    id: '14',
  },
  {
    age: '21',
    gender: 'male',
    occupation: 'Intern',
    hobbies: ['Learning', 'Reading'],
    email: 'chris@example.com',
    phone: '333-111-9999',
    username: 'chrisI21',
    name: 'Chris Lewis',
    country: 'Netherlands',
    id: '15',
  },
  {
    age: '36',
    gender: 'female',
    occupation: 'CEO',
    hobbies: ['Gambling', 'Traveling'],
    email: 'emily@example.com',
    phone: '444-222-0000',
    username: 'emilyC36',
    name: 'Emily Robinson',
    country: 'Sweden',
    id: '16',
  },
  {
    age: '37',
    gender: 'male',
    occupation: 'Doctor',
    hobbies: ['Helping others', 'Running'],
    email: 'david@example.com',
    phone: '555-333-1111',
    username: 'davidD37',
    name: 'David Hall',
    country: 'Norway',
    id: '17',
  },
  {
    age: '38',
    gender: 'female',
    occupation: 'Accountant',
    hobbies: ['Calculating', 'Reading'],
    email: 'olivia@example.com',
    phone: '666-444-2222',
    username: 'oliviaA38',
    name: 'Olivia Young',
    country: 'Finland',
    id: '18',
  },
  {
    age: '39',
    gender: 'male',
    occupation: 'Plumber',
    hobbies: ['Fixing pipes', 'Fishing'],
    email: 'noah@example.com',
    phone: '777-555-3333',
    username: 'noahP39',
    name: 'Noah King',
    country: 'Denmark',
    id: '19',
  },
  {
    age: '40',
    gender: 'female',
    occupation: 'Teacher',
    hobbies: ['Teaching', 'Traveling'],
    email: 'ava@example.com',
    phone: '888-666-4444',
    username: 'avaT40',
    name: 'Ava Scott',
    country: 'Belgium',
    id: '20',
  },
];

const meta: Meta<typeof SmartTable> = {
  title: 'Smart Table',
  component: SmartTable,
  argTypes: {
    columns: { control: false },
    data: { control: false },
    width: { control: 'inline-radio', options: ['scroll', 'content'] },
    selectable: { control: 'boolean' },
    rowId: { control: false },
  },
  args: {},
  decorators: [
    Story => (
      <div style={{ width: '100%', maxHeight: '500px', overflow: 'auto' }}>
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof SmartTable>;

export const Users: Story = {
  args: {
    // @ts-expect-error Storybook doesn't recognize the rowId prop
    rowId: 'id',
    data: users,
    columns: [
      // @ts-expect-error Storybook doesn't recognize props
      { header: 'Name', field: 'name' },
      // @ts-expect-error Storybook doesn't recognize props
      { header: 'Age', field: 'age' },
      // @ts-expect-error Storybook doesn't recognize props
      { header: 'Email', field: 'email' },
      // @ts-expect-error Storybook doesn't recognize props
      { header: 'Username', field: 'username' },
      // @ts-expect-error Storybook doesn't recognize props
      { header: 'Phone', field: 'phone' },
      {
        header: 'Gender',
        // @ts-expect-error Storybook doesn't recognize props
        render: data => (data.gender === 'male' ? <FaUser /> : <FaCamera />),
        // @ts-expect-error Storybook doesn't recognize props
        sortBy: 'gender',
      },
      // @ts-expect-error Storybook doesn't recognize props
      { header: 'Country', field: 'country' },
      // @ts-expect-error Storybook doesn't recognize props
      { header: 'Occupation', field: 'occupation' },
    ],
  },
};
