#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the current branch name
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Check if the current branch is 'master'
if [ "$current_branch" = "master" ]; then
  echo "Skipping post-merge hook on master branch."
  exit 0 # Exit successfully without running further commands
fi

pnpm lint-commit
